import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Auth App",
  description: "Generated by create next app v13",
};

interface IRootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: IRootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={false}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
