"use client";

import { useEffect } from "react";
import "./globals.css";
import { Inter } from "next/font/google";
import { usePathname, useSearchParams } from "next/navigation";
import { NextAuthProvider } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: IRootLayoutProps) {
  const pathname = usePathname();

  useEffect(() => {
    const url = `${pathname}`;
    console.log(url);
  }, [pathname]);

  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={false}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
