import { useSession } from "next-auth/react";
import { SessionProvider } from "next-auth/react";
import type { Session } from "next-auth";
import { NextAuthProvider } from "./provider";

interface ILayoutProps {
  children: React.ReactNode;
}

export const metadata = {
  title: "Dashboard App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }: ILayoutProps) {
  return <NextAuthProvider>{children}</NextAuthProvider>;
}
